"""Column layout of the stock V2.57 SQLite databases as observed in the disposable guest.

Synthetic fixture only: the same tables and columns, no vendor data. Used to prove
every reviewed query executes against the schema and by the data-level tests.
"""
import sqlite3

SONG_COLUMNS = ('ID INTEGER PRIMARY KEY AUTOINCREMENT, PATH TEXT, NAME TEXT, TITLE TEXT, ALBUM TEXT, ARTIST TEXT, GENRE TEXT, DISC INTEGER, TRACK INTEGER, '
                'IS_CUE INTEGER, IS_ISO INTEGER, IS_DSD INTEGER, OFFSET INTEGER, DURATION INTEGER, NAME_CODE INTEGER, TITLE_CODE INTEGER, ALBUM_CODE INTEGER, '
                'ARTIST_CODE INTEGER, GENRE_CODE INTEGER, ADD_TIME INTEGER, SAMPLE_RATE INTEGER, BIT_PER_SAMPLE INTEGER, CHANNELS INTEGER, BIT_RATE INTEGER, '
                'SONG_MIMETYPE TEXT, SONG_PRODUCTION_YEAR TEXT, IS_SELECT INTEGER, ALBUM_ARTIST TEXT, ALBUM_ARTIST_CODE INTEGER, IS_M3U INTEGER, M3U_PATH TEXT, '
                'NAME_CODE_JP INTEGER, TITLE_CODE_JP INTEGER, ALBUM_CODE_JP INTEGER, ARTIST_CODE_JP INTEGER, GENRE_CODE_JP INTEGER, ALBUM_ARTIST_CODE_JP INTEGER')
SYSCONFIG_COLUMNS = ('ID INTEGER PRIMARY KEY AUTOINCREMENT, DSD_MODE, OUT_DEV, VOLUME, WORK_MODE, LIGHT_LEVEL, LIGTH_ON_TIME, RGB_LEVEL, MUTE, VOL_MODE, RGB_STATUS, '
                     'RGB_COLOUR, TRIGGER_IN, SYS_THEME, LANGUAGE, USB_MODE, NETWORK_MODE, EQ_TYPE, MAX_VOL, BALANCE_VOL, POWER_SAVE, FILTER_TYPE, PLAY_MODE, '
                     'MEMORY_PLAY, FOLDER_JUMP, PLAY_GAP, INPUT_MODE, VOL_KNOB_MODE, OTA_CFG, BATTERY, BT_CODEC, SCREEN_ROT, PO_PRE_VOL, PO_VOL, PRE_VOL, THEME_MODE, '
                     'CHARGE_PROTECT, LOCK_THEME, TREBLE, BASS, WIFI_STATUS, BT_STATUS, LO_DISABLE, OS_MODE, DSD_DECODE, SPDIF, AUTO_TIME, DRE_STATUS, DEVICE_OUTPUT, '
                     'LOCAL_IMG_ANIM, IMG_ANIM_BRIGHTNESS, ARM_VERSION, MCU_OTA_FAILED_TIME, KEY_SINGLE_CLICK_SLE, KEY_DOUBLE_CLICK_SLE, KEY_LONG_PRESS_SLE, '
                     'ARTIST_CLASS_TYPE, AUDIO_VOLUME_SET, SYS_REPLAY_GAIN, ONLINE_COVER, ONLINE_LRC, TRACK_DISPLAY, FONT_SIZE, BTSINK_VOLUME, BT_SRC_VOLUME, '
                     'UAC_VOLUME, AIRPLAY_MEM_VOLUME, LIST_OPER_MODE')
SCHEMA = {
    'song.db': [
        f'CREATE TABLE SONG ({SONG_COLUMNS})',
        f'CREATE TABLE MY_LOVE ({SONG_COLUMNS}, UNIQUE(PATH, TRACK))',
        f'CREATE TABLE CUSTOM_PLAYLIST (ID INTEGER PRIMARY KEY AUTOINCREMENT, PLAYLIST_ID INTEGER, {SONG_COLUMNS.split(", ", 1)[1]})',
        'CREATE TABLE CUSTOM_PLAYLIST_INDEX (ID INTEGER PRIMARY KEY AUTOINCREMENT, LIST_ID INTEGER, LIST_NAME TEXT, M3U_PATH TEXT)',
        'CREATE TABLE LIST_SONG_0 (ID INTEGER PRIMARY KEY AUTOINCREMENT, LIST_ID INTEGER, POS_ID INTEGER, PATH TEXT, NAME TEXT, TITLE TEXT, ALBUM TEXT, ARTIST TEXT, GENRE TEXT, DISC INTEGER, TRACK INTEGER, IS_CUE INTEGER, IS_ISO INTEGER, OFFSET INTEGER, DURATION INTEGER, ADD_TIME INTEGER, IS_SELECT INTEGER, SONG_TYPE INTEGER, ALBUM_ARTIST TEXT, IS_M3U INTEGER, M3U_PATH TEXT)',
        'CREATE TABLE MEMORY_PLAY (ID INTEGER PRIMARY KEY AUTOINCREMENT, MUSIC_ID INTEGER, IS_PLAYING INTEGER, POSITION INTEGER, IS_CUE INTEGER, IS_ISO INTEGER, TRACK INTEGER, IS_NAS INTEGER, IS_M3U INTEGER)',
        'CREATE TABLE PEQ (ID INTEGER PRIMARY KEY AUTOINCREMENT, STYLE_NAME TEXT, MASTER_GAIN REAL, PARAMS_JSON TEXT, STYLE_PRESET INTEGER)',
        'CREATE TABLE PLAY_LIST (ID INTEGER PRIMARY KEY AUTOINCREMENT, LIST_ID INTEGER, LIST_NAME TEXT)',
        'CREATE TABLE RECORD_SONG (ID INTEGER PRIMARY KEY AUTOINCREMENT, PATH TEXT, NAME TEXT, TITLE TEXT, ALBUM TEXT, ARTIST TEXT, ALBUM_ARTIST TEXT, GENRE TEXT, DISC INTEGER, TRACK INTEGER, DURATION INTEGER, IS_CUE INTEGER, IS_ISO INTEGER, OFFSET INTEGER, IS_M3U INTEGER, M3U_PATH TEXT, PLAY_COUNT INTEGER, LAST_PLAY_TIME INTEGER)',
    ],
    'sysconfig.db': [f'CREATE TABLE SYSCONFIG ({SYSCONFIG_COLUMNS})'],
    'theme.db': ['CREATE TABLE CUSTOM_THEME (ID INTEGER PRIMARY KEY AUTOINCREMENT, POS_ID INTEGER, NAME TEXT, PATH TEXT, ALIAS TEXT, TYPE INTEGER, USE INTEGER, IS_SYSTEM INTEGER, ATTR INTEGER, SUBCLASS INTEGER, ALPHA INTEGER, LOCK_TIME INTEGER, LOCK_DATE INTEGER, LOCK_BATTERY INTEGER, LOCK_ID3 INTEGER, LOCK_MEM_TYPE INTEGER, FRONT_COLOR TEXT, PREVIEW_PATH TEXT)'],
}


def create(directory, populate=True):
    """Creates the three fixture databases under directory with a few synthetic rows."""
    for name, statements in SCHEMA.items():
        con = sqlite3.connect(str(directory / name))
        for statement in statements:
            con.execute(statement)
        if populate:
            if name == 'sysconfig.db':
                con.execute('INSERT INTO SYSCONFIG (LANGUAGE, SYS_THEME, FONT_SIZE, BATTERY, POWER_SAVE, VOLUME, MAX_VOL, VOL_MODE, FILTER_TYPE, PLAY_MODE, WORK_MODE, INPUT_MODE, BT_CODEC) VALUES (9, 0, 0, 87, 300, 40, 120, 1, 1, 0, 0, 1, 3)')
            elif name == 'song.db':
                for i, title in enumerate(('Первый — Ё', 'Second', 'Third'), start=1):
                    con.execute('INSERT INTO SONG (PATH, NAME, TITLE, ALBUM, ARTIST, GENRE, DURATION, ADD_TIME, SAMPLE_RATE, BIT_PER_SAMPLE, CHANNELS) VALUES (?,?,?,?,?,?,?,?,?,?,?)',
                                (f'/tmp/sdcard/CI/{title}.flac', f'{title}.flac', title, 'CI Album', 'CI Artist', 'Rock', 30000 * i, 1790000000 + i, 44100, 16, 2))
                con.execute("INSERT INTO MY_LOVE (PATH, NAME, TITLE, ALBUM, ARTIST) VALUES ('/tmp/sdcard/CI/Second.flac', 'Second.flac', 'Second', 'CI Album', 'CI Artist')")
                con.execute("INSERT INTO CUSTOM_PLAYLIST_INDEX (LIST_ID, LIST_NAME) VALUES (7, 'Evening')")
                con.execute("INSERT INTO CUSTOM_PLAYLIST (PLAYLIST_ID, PATH, NAME, TITLE) VALUES (7, '/tmp/sdcard/CI/Third.flac', 'Third.flac', 'Third')")
                con.execute("INSERT INTO LIST_SONG_0 (PATH, NAME, SONG_TYPE) VALUES ('/tmp/sdcard/CI/Second.flac', 'Second.flac', 3)")
                con.execute('INSERT INTO MEMORY_PLAY (MUSIC_ID, IS_PLAYING, POSITION) VALUES (2, 1, 28000)')
                con.execute("INSERT INTO RECORD_SONG (PATH, NAME, PLAY_COUNT, LAST_PLAY_TIME) VALUES ('/tmp/sdcard/CI/Second.flac', 'Second.flac', 3, 1790001000)")
                con.execute("INSERT INTO PEQ (STYLE_NAME, MASTER_GAIN, PARAMS_JSON, STYLE_PRESET) VALUES ('', 0.0, '(null)', 160)")
            else:
                con.execute("INSERT INTO CUSTOM_THEME (POS_ID, NAME, ALIAS, TYPE, USE, IS_SYSTEM, PATH) VALUES (0, 'watch_dial_3.png', 'Clock', 200, 1, 1, '/usr/project/config/img/x.png')")
        con.commit(); con.close()
