#!/usr/bin/env python3
"""Embed the application manager's page (device/manager) in the gateway; no runtime file reads."""
from pathlib import Path
import sys

root = Path(__file__).resolve().parent.parent
out = Path(sys.argv[1])
out.parent.mkdir(parents=True, exist_ok=True)
items = [('index.html', '/', 'text/html; charset=utf-8'), ('manager.js', '/manager.js', 'text/javascript; charset=utf-8'),
         ('manager.css', '/manager.css', 'text/css; charset=utf-8')]
parts = ['/* Generated by scripts/embed-manager.py from device/manager. */']
for i, (name, _, _) in enumerate(items):
    data = (root/'device/manager'/name).read_bytes()
    parts.append(f'static const unsigned char manager_asset_{i}[] = {{{",".join(map(str, data))}}};')
parts.append('static const struct {const char *path, *type; const unsigned char *data; size_t size;} manager_assets[] = {')
for i, (_, path, mime) in enumerate(items):
    parts.append(f'{{"{path}", "{mime}", manager_asset_{i}, sizeof(manager_asset_{i})}},')
parts.append('};')
text = '\n'.join(parts) + '\n'
if not out.exists() or out.read_text() != text:
    out.write_text(text)
