#!/usr/bin/env python3
"""Embed only the probe assets; no runtime filesystem server."""
from pathlib import Path
import sys
from firmware_profile import load_profile
from app_bundle import compatibility_data
root = Path(__file__).resolve().parent.parent
out = Path(sys.argv[1]); out.parent.mkdir(parents=True, exist_ok=True)
items = [('index.html', '/', 'text/html; charset=utf-8'), ('style.css', '/style.css', 'text/css'), ('app.js', '/app.js', 'text/javascript'), ('protocol.mjs', '/protocol.mjs', 'text/javascript'), ('compatibility.json', '/compatibility.json', 'application/json')]
parts = ['/* Generated by scripts/embed-assets.py. */']
for i, (name, _, _) in enumerate(items):
    data = compatibility_data(load_profile()) if name == 'compatibility.json' else (root/'apps/probe'/name).read_bytes()
    parts.append(f'static const unsigned char asset_{i}[] = {{{",".join(map(str, data))}}};')
parts.append('static const struct {const char *path, *type; const unsigned char *data; size_t size;} assets[] = {')
for i, (_, path, mime) in enumerate(items):
    parts.append(f'{{"{path}", "{mime}", asset_{i}, sizeof(asset_{i})}},')
parts.append('};')
out.write_text('\n'.join(parts)+'\n')
